### ISSUE TITLE
Plan for lanseringsklart

### ISSUE THREAD

**Issue by henrist** [blindern/billett#11]
Hva må på plass?

Overordnet minstekrav:
- Besøkende må kunne gjennomføre bestilling av billett på nettsiden

Detaljfunksjonalitet:
- [x] Gjennomføre bestilling via nettsiden #6
- [x] Integrasjon mot betalingsleverandør #5
- [x] Få tilsendt bookingbekreftelse på e-post #14
- [x] Generering og sending av PDF-billetter #4
- [x] API for den vanlige nettsiden (for å integrere programmet der) #15
