### ISSUE TITLE
Plan for administrasjon del 1

### ISSUE THREAD

**Issue by henrist** [blindern/billett#8]
Hva må på plass?

Overordnet krav:
- Mulighet til å legge til og redigere arrangementer
- Opprette og redigere billettgrupper tilhørende arrangementer

Siden vi sannsynligvis ikke har noen innloggingsløsning på plass til dette målet, vil ting være IP-begrenset og manuell tilgangsliste må opprettes.

Detaljert funksjonalitet:
- [x] Detaljert liste over arrangementer #16
- [x] Opprette nye arrangementer tilhørende arrangementgruppe #17
- [x] Redigere eksisterende arrangementer #18, #19, #20
- [x] Slette arrangementer uten gyldige billetter #21
- [x] Opprette billettgruppe tilhørende arrangement #22
- [x] Redigere eksisterende billettgruppe uten eksisterende billetter #23
- [x] Slette billettgrupper uten eksisterende billetter #24
